# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            5
paginate_path: 		 "blog/page:num/"
baseurl:             ""


# About/contact
author:
  name:              Daniel Pfeiffer
  url:               http://danielpfeiffer.me
  email:             mail@danielpfeiffer.me

gems: 
                     - jekyll-paginate
